### ISSUE TITLE
Make token validation pluggable

### ISSUE THREAD

**Issue by travisspencer** [curityio/example-python-openid-connect-client#1]
The validation of tokens assumes that the token will always be a JWT. This should be extended to support reference tokens and other types. The actual validator type should be configured along with the other settings. Support for opaque, reference tokens should be possible via configuration.

**Comment by travisspencer** [comment]
Looking deeper, I don't know that this feature makes sense. The client is only validating ID tokens and those will always be JWTs ([per the spec](http://openid.net/specs/openid-connect-core-1_0.html#IDToken)). It's [in the API](https://github.com/curityio/oauth-filter-for-python-flask) that we need to make the token validation pluggable, right @daniellindau? Looks like @jacob-curityio has already done that. If correct, I'll close this as "won't fix".

**Comment by daniellindau** [comment]
It's only validating the ID token, and the access token doesn't make much sense to validate for the client. The api is validating access token and JWTs if I'm not mistaken, so I agree on closing with won't fix. @travisspencer
