### ISSUE TITLE
HMAC signature validation does'nt use client's secret

### ISSUE THREAD

**Issue by fredmurdoc** [curityio/example-python-openid-connect-client#15]
The set of keys used to validate signatures doest load client's secret. The set of keys includes only keys declared in then endpoint jwks.

**Comment by travisspencer** [comment]
Curity doesn't support signing JWTs with a client secret, so this has never come up. Thanks for reporting it. Out of curiosity, which OAuth server has this created interop issues with?

**Comment by fredmurdoc** [comment]
I've used LemonLDAP as OpenID Connect Identity Provider

**Comment by travisspencer** [comment]
Great, @fredmurdoc . Thanks for the extra testing and bug fix. I've merged it, so closing this issue.
