### ISSUE TITLE
issues when trying to run in http only

### ISSUE THREAD

**Issue by v4rp1ng** [curityio/example-python-openid-connect-client#44]
Hi,

I had some issues when I tried to run it on http only mode. My base_url in settings.json was not set and in app.py it defaults to the https link. 

in app.py line 439:
```
if 'base_url' not in _config:
        _config['base_url'] = 'https://localhost:%i' % port
```

here we should implement a check if _disable_https == True the _config['base_url'] should default to 'http://...'.

Also on line 135:
in @_app.route('/logout') the base_url is not encoded and will throw an error for redirection in the browser.
`logout_request = _config['end_session_endpoint'] + '?client_id=' + _config['client_id'] + '&post_logout_redirect_uri=' + _config['base_url']`

_config['base_url'] needs to be encoded.

Anyway, thanks I learned a lot with this example. :)

**Comment by mtrojanowski** [comment]
Hi @v4rp1ng

Thanks for your comments. We're glad that the example helped you learn about OAuth and OIDC.

I changed the default base_url creation and now it takes the disable_https flag into consideration. Note however that the best practice is to always use https. With the simple tools available nowadays and services like letsencrypt, it is really straightforward to put your apps behind https. (E.g. in this example the dev certificates are created automatically, you just have to add security exceptions in your browser as they're self-signed)

I also added encoding to the base_url when used in the logout URI. However, I haven't seen an issue with an unencoded value used here. I tested that on python 3.9 and Firefox.
