### ISSUE TITLE
Support for TLS 1.2

### ISSUE THREAD

**Issue by stefer** [curityio/example-python-openid-connect-client#7]
Hi, We have restricted all our sites to use only TLS 1.2.

This is not supported by default by Python ssl module.
I tried to patch the get_ssl_context, but my python is a bit rusty.

```
def get_ssl_context(config):
    """
    :return a ssl context with verify and hostnames settings
    """
    ctx = ssl.create_default_context()
      // should do something like this instead ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)

    if 'verify_ssl_server' in config and not bool(config['verify_ssl_server']):
        print 'Not verifying ssl certificates'
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE
    return ctx
```

**Comment by daniellindau** [comment]
Are you using the default Mac OS X python version? It is built against a openssl that does not support TLS 1.2. We usually use the homebrew python to get that functionality.

**Comment by daniellindau** [comment]
What openssl version is running then, the example need at least 1.0.

To check, you can run this in the python console:
```
~> python
Python 2.7.13 (default, Apr  4 2017, 10:04:44)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> ssl.OPENSSL_VERSION
'OpenSSL 1.0.2l  25 May 2017'
```

**Comment by stefer** [comment]
This seem to be another problem. When I test against howmyssl, it reports TLS 1.2 support.
We now suspect our firewall to stop the traffic.

`    
    >>> import json, urllib2
    >>> json.load(urllib2.urlopen('https://www.howsmyssl.com/a/check'))['tls_version']
    u'TLS 1.2'
`
